version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_database_name
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres_user
      DB_PASSWORD: postgres_password
      DB_NAME: postgres_database_name
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
